# ZenithQ Configuration File
# Copy this to config.yaml and fill in your API keys and settings

# Data Sources
data_sources:
  alpaca:
    api_key: "YOUR_ALPACA_API_KEY"
    secret_key: "YOUR_ALPACA_SECRET_KEY"
    base_url: "https://paper-api.alpaca.markets"  # Use paper trading initially
    
  yfinance:
    enabled: true
    
  ccxt:
    exchanges:
      - name: "binance"
        api_key: "YOUR_BINANCE_API_KEY"
        secret: "YOUR_BINANCE_SECRET"
        sandbox: true
        
  news:
    twitter_bearer_token: "YOUR_TWITTER_BEARER_TOKEN"
    news_api_key: "YOUR_NEWS_API_KEY"
    
# Database Configuration
database:
  postgres:
    host: "localhost"
    port: 5432
    database: "zenithq"
    username: "zenithq_user"
    password: "YOUR_DB_PASSWORD"
    
  redis:
    host: "localhost"
    port: 6379
    password: "YOUR_REDIS_PASSWORD"
    db: 0
    
# ML Configuration
ml_config:
  models:
    traditional:
      - xgboost
      - random_forest
      - svm
      
    deep_learning:
      - lstm
      - gru
      - tcn
      - transformer
      
    reinforcement_learning:
      - dqn
      - ppo
      - a3c
      
  training:
    batch_size: 32
    epochs: 100
    learning_rate: 0.001
    validation_split: 0.2
    
  genetic_algorithm:
    population_size: 50
    generations: 100
    mutation_rate: 0.1
    crossover_rate: 0.8
    
# Backtesting Configuration
backtesting:
  start_date: "2020-01-01"
  end_date: "2023-12-31"
  initial_capital: 100000
  commission: 0.001  # 0.1%
  slippage: 0.0005   # 0.05%
  
# Risk Management
risk_management:
  max_position_size: 0.1  # 10% of portfolio
  max_daily_loss: 0.02    # 2% daily loss limit
  max_drawdown: 0.15      # 15% max drawdown
  kelly_fraction: 0.25    # Kelly criterion multiplier
  
  position_sizing:
    method: "kelly"  # options: fixed, kelly, volatility_target
    
  stop_loss:
    enabled: true
    percentage: 0.02  # 2% stop loss
    
  take_profit:
    enabled: true
    ratio: 2.0  # 2:1 reward to risk ratio
    
# Strategy Configuration
strategies:
  momentum:
    timeframes: ["1h", "4h", "1d"]
    indicators:
      - macd
      - rsi
      - ema
      
  mean_reversion:
    timeframes: ["15m", "1h", "4h"]
    indicators:
      - bollinger_bands
      - rsi
      - z_score
      
  price_action:
    timeframes: ["1h", "4h", "1d"]
    patterns:
      - engulfing
      - pin_bar
      - breakout
      
# Dashboard Configuration
dashboard:
  host: "0.0.0.0"
  port: 8000
  debug: false
  
# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/zenithq.log"
  
# Monitoring
monitoring:
  prometheus:
    enabled: true
    port: 9090
    
  alerts:
    email:
      smtp_server: "smtp.gmail.com"
      smtp_port: 587
      username: "YOUR_EMAIL"
      password: "YOUR_EMAIL_PASSWORD"
      
# Live Trading (DANGER ZONE)
live_trading:
  enabled: false  # NEVER enable without thorough testing
  max_daily_trades: 10
  max_concurrent_positions: 5
  
# Paper Trading
paper_trading:
  enabled: true
  initial_balance: 100000
  
# Symbols to Trade
symbols:
  stocks:
    - "AAPL"
    - "GOOGL"
    - "MSFT"
    - "TSLA"
    - "AMZN"
    
  forex:
    - "EURUSD"
    - "GBPUSD"
    - "USDJPY"
    
  crypto:
    - "BTCUSD"
    - "ETHUSD"
    - "ADAUSD" 